---
apiVersion: v1
kind: Secret
metadata:
  name: <service_account_name>-token
  namespace: <namespace>
  annotations:
    kubernetes.io/service-account.name: <service_account_name>
type: kubernetes.io/service-account-token