---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: apps-dev
  labels:
    userType: bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-deployer-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cicd-deployer
    namespace: apps-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: cicd-deployer-token
  namespace: apps-dev
  annotations:
    kubernetes.io/service-account.name: cicd-deployer
type: kubernetes.io/service-account-token
