---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-dev-deployer
  namespace: apps-dev
  labels:
    userType: bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: apps-dev
rules:
  - apiGroups: ["apps", ""]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - configmaps
      - services
      - secrets
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-dev-deployer-binding
  namespace: apps-dev
subjects:
  - kind: ServiceAccount
    name: cicd-dev-deployer
    namespace: apps-dev
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: cicd-dev-deployer-token
  namespace: apps-dev
  annotations:
    kubernetes.io/service-account.name: cicd-dev-deployer
type: kubernetes.io/service-account-token
